name: Test Coveralls

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x

            - run: npm ci

            - name: generate report
              run: npm run report

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
