name: 'Code Linting'

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        name: Lint codebase
        steps:
            - uses: actions/checkout@v1
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: '10'
            - run: npm ci
            - run: npm run lint
