name: 'Integration Tests'

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['10', '8']
        name: Test with Node version ${{ matrix.node }}
        steps:
            - uses: actions/checkout@v1
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - run: npm ci
            - run: npm start-test
            - run: npm test
